### ISSUE TITLE
How to specify a file for app-settings-json?

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure/appservice-settings#15]
Is it possible to specify a JSON file in my repository and pass it to the `app-settings-json` parameter?

Something like this:

```yaml
- name: Configure app settings
  uses: Azure/appservice-settings@v1
  with:  
    app-name: ${{ env.WEBAPP_NAME }}
    app-settings-json: config/app-settings.json
```

**Comment by aksm-ms** [comment]
@JasonFreeberg currently it is not supported.

**Comment by aksm-ms** [comment]
Closing the issue. Feel free to reopen in case of any queries.

**Comment by dmcconnell-m** [comment]
For anyone that comes across this, I implemented a workaround for this with:

```
    #read the json from the file into a variable and remove all new line characters
    - run: echo "::set-output name=appsettings_json::$(tr -d '\n' < ${{ env.MY_FILE_PATH }})"
      id: load-json

    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        app-settings-json: '${{ steps.load-json.outputs.appsettings_json }}' 
      id: settings
```
The trick is that you need to remove new lines so its a single line json so this action can read in the whole json string
