### ISSUE TITLE
Why do I keep getting "Error: App Service Settings is not enabled."?

### ISSUE THREAD

**Issue by cfofiu** [Azure/appservice-settings#24]
I keep getting "Error: App Service Settings is not enabled." and I do not understand why?

```
Run azure/appservice-settings@v1
  with:
    app-name: joinjoiya-stage
    mask-inputs: false
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
***
Error: Error: App Service Settings is not enabled. Please provide one of the following : App Settings or General Settings or Connection Strings.
```

Here's part of my `yaml`:
```
    - uses: azure/appservice-settings@v1
      with:
        app-name: 'monogram-joiya-test'
        mask-inputs: false
        app-settings-json: '${{ secrets.NEXT_PUBLIC_DISPLAY_ENV }}'
      id: settings
    - run: echo "The NEXT_PUBLIC_DISPLAY_ENV is... ${{ steps.settings }}"
```
