### ISSUE TITLE
Can we add an argument for this action to place environment variables into the App Service slot container?

### ISSUE THREAD

**Issue by KalvinWei** [Azure/appservice-settings#53]
For example:
```YAML
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - name: npm install, build
        run: yarn install --frozen-lockfile && yarn build
      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
          app-settings: '{"ENV_VAR1":value, "ENV_VAR2":value}'  # add something like this to inject env vars to the container
```
